---
- name: Clean project directory
  file:
    path: "{{ laravel_project_path }}"
    state: absent
  become: true
  ignore_errors: true

- name: Create project directory
  file:
    path: "{{ laravel_project_path }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Install Laravel project
  command: |
    composer create-project laravel/laravel:^11 . --prefer-dist --no-interaction --no-plugins
  args:
    chdir: "{{ laravel_project_path }}"
    creates: "{{ laravel_project_path }}/artisan"
  environment:
    COMPOSER_MEMORY_LIMIT: -1
  become: false

- name: Set correct permissions
  file:
    path: "{{ laravel_project_path }}"
    owner: www-data
    group: www-data
    recurse: true
  become: true