---
- name: Install base tools
  apt:
    name:
      - software-properties-common
      - ca-certificates
      - apt-transport-https
      - lsb-release
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Add PHP PPA (Ondrej)
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  register: php_ppa

- name: Update apt cache if PPA changed
  apt:
    update_cache: yes
  when: php_ppa is changed

# fpm, curl, xml, mbstring, gd, imagick, imap, intl, mysqli(=mysql pkg), pgsql, zip
- name: Install PHP {{ php_version }} + extensions
  apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mysql"  
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-zip"
    state: present

- name: Ensure PHP-FPM is enabled & running
  service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes
